AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Template Repo

Resources:
  PythonLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: layer/.
      CompatibleRuntimes:
        - python3.6
        - python3.7
        - python3.8
      LicenseInfo: "MIT"
      RetentionPolicy: Delete
    Metadata:
      BuildMethod: python3.6

  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: my-function/
      Handler: app.lambda_handler
      Runtime: python3.6
      Layers:
        - !Ref PythonLayer
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /
            Method: get
